// Proposer in stub mode: a valid, grounded candidate set with the required case mix, economics
// computed by code, and the blind-label table in candidates.md.
import { test, describe, before } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { setLlmContext } from "../src/core/llm.ts";
import { load } from "../src/core/io.ts";
import { Candidates, type Proposal } from "../src/core/schema.ts";
import { proposalEconomics } from "../src/model/economics.ts";
import { propose, revise, keyScreens } from "../src/propose/propose.ts";
import { validateSet } from "../src/propose/validate.ts";
import { fromLlmProposal, normalizeStoryboard, toLlmProposal } from "../src/propose/schemas.ts";
import { resolveAnchors, sizeReward } from "../src/propose/anchors.ts";
import { stubRevise } from "../src/propose/stub.ts";
import { codeGates } from "../src/judge/gates.ts";
import { sampleModel } from "./helpers/sample-model.ts";
import { ctx, noScarcityModel, tmpDir } from "./helpers/proposejudge-ctx.ts";

setLlmContext({ mode: "stub" });

describe("propose (stub)", () => {
  const m = sampleModel();
  const out = tmpDir("propose");
  let cands: Candidates;
  before(async () => { cands = await propose(ctx(out), m); });

  test("writes schema-valid candidates marked as stub output", () => {
    const file = path.join(out, "sample", "proposals", "candidates.json");
    const disk = load(Candidates, file);
    assert.equal(disk.generatedBy, "stub");
    assert.equal(disk.proposals.length, ctx(out).profile.proposals);
    assert.deepEqual(disk.proposals.map(p => p.id), ["P1", "P2", "P3", "P4"]);
  });

  test("the idea set passes validateSet with >= 3 existing and >= 3 product-change", () => {
    assert.deepEqual(validateSet(cands, m), []);
    assert.ok(cands.ideas.filter(i => i.case === "existing").length >= 3);
    assert.ok(cands.ideas.filter(i => i.case === "product-change").length >= 3);
    assert.equal(cands.ideas.length, ctx(out).profile.candidates);
    assert.equal(cands.baseline.length, 3);
    assert.deepEqual(cands.momentSweep.map(s => s.moment), m.moments.map(x => x.id));
    assert.equal(cands.momentSweep.find(s => s.moment === "m6")?.viable, false, "first-value is never viable");
  });

  test("economics are filled by code, never by the proposer", () => {
    for (const p of cands.proposals) {
      assert.ok(p.economics, p.id);
      assert.deepEqual(p.economics, proposalEconomics({ ...p, economics: undefined }, m));
    }
  });

  test("every proposal is grounded in the model and structurally complete", () => {
    for (const p of cands.proposals) {
      const failed = codeGates(p, m).filter(g => !g.pass && g.gate !== "economics");
      assert.deepEqual(failed, [], `${p.id}: ${failed.map(g => `${g.gate}: ${g.evidence}`).join(" | ")}`);
      assert.deepEqual(p.storyboard.map(b => b.phase), ["today", "change", "offer", "ad", "value"]);
      assert.equal(p.reward.grantOn, "REWARD_VERIFIED");
      assert.ok(!p.anchor.moments.includes("m6"), "never on the first-value moment");
    }
  });

  test("the wall refill is sized with the exchange rate (one cheapest action)", () => {
    const wall = cands.proposals.find(p => p.archetype === "TAX-1")!;
    assert.equal(wall.surface, "s04");
    assert.equal(wall.reward.resource, "r1");
    assert.equal(wall.reward.amount, 10);
    assert.deepEqual(wall.economics!.flags, []);
    assert.deepEqual(sizeReward(m, "r1"), { amount: 10, buys: "one message in Basic mode", cogs: "text-cheap", cogsUnits: 1 });
  });

  test("candidates.md has the blind-label table with an empty label column", () => {
    const md = fs.readFileSync(path.join(out, "sample", "proposals", "candidates.md"), "utf8");
    assert.match(md, /your label \(SHIP\/REVISE\/REJECT\)/);
    const row = md.split("\n").find(l => l.startsWith("| P1 |"))!;
    assert.match(row, /\|\s+\|$/, "the label cell is empty");
    assert.match(md, /Generated by the deterministic stub/);
    assert.match(md, /## Moment sweep/);
    assert.match(md, /## The obvious baseline/);
  });

  test("key screenshots follow walls, declines, post-reward, desire and hubs", () => {
    assert.deepEqual(keyScreens(m), ["s04", "s06", "s03", "s01", "s05"]);
  });
});

describe("propose helpers", () => {
  const m = sampleModel();

  test("validateSet reports each violated rule", () => {
    const idea = (moment: string, reward: string, over: Partial<{ case: "existing" | "product-change"; archetype: string; beyondBaseline: boolean }> = {}) =>
      ({ title: "t", case: "existing" as const, archetype: "TAX-1", moment, reward, beyondBaseline: false, ...over });
    const v = validateSet({ ideas: [idea("m1", "+10"), idea("m1", "+10"), idea("m6", "x"), idea("m9", "y")], selected: [{ index: 7, why: "" }] }, m);
    const has = (re: RegExp) => assert.ok(v.some(x => re.test(x)), `${re} in ${v.join(" | ")}`);
    has(/at least 3 "product-change"/);
    has(/at least 4 distinct archetypes/);
    has(/m6, a first-value moment/);
    has(/"m9", which is not a moment id/);
    has(/proactive idea/);
    has(/At least half/);
    has(/repeat the same \(moment, reward\)/);
    has(/out of range: 7/);
  });

  test("no-scarcity models get >= 5 product changes and still pass validateSet", async () => {
    const ns = noScarcityModel();
    assert.equal(ns.regime, "no-scarcity");
    const cands = await propose(ctx(tmpDir("propose-ns")), ns);
    assert.deepEqual(validateSet(cands, ns), []);
    assert.ok(cands.ideas.filter(i => i.case === "product-change").length >= 5);
    for (const p of cands.proposals) assert.deepEqual(codeGates(p, ns).filter(g => !g.pass).map(g => g.evidence), [], p.id);
  });

  test("the LLM proposal shape round-trips and the storyboard is repaired to 5 phases", async () => {
    const [p] = (await propose(ctx(tmpDir("propose-rt")), m)).proposals;
    const back = fromLlmProposal(toLlmProposal(p), p.id, p.version);
    // `verified` is set by code after every model call, so the model-facing shape drops it.
    const unverified = (x: Proposal) => ({ ...x, economics: undefined, evidence: x.evidence.map(e => ({ ...e, verified: false })) });
    assert.deepEqual(unverified(back), unverified(p));
    const broken: Proposal = { ...p, storyboard: [p.storyboard[2], p.storyboard[0], p.storyboard[0]] };
    const fixed = normalizeStoryboard(broken);
    assert.ok(fixed.repaired);
    assert.deepEqual(fixed.storyboard.map(b => b.phase), ["today", "change", "offer", "ad", "value"]);
  });

  test("the stub reviser resizes an over-generous reward to the exchange rate and bumps the version", async () => {
    const cands = await propose(ctx(tmpDir("propose-rev")), m);
    const dbl = cands.proposals.find(p => p.archetype === "TAX-5")!;
    assert.equal(dbl.reward.amount, 300);
    assert.ok(dbl.economics!.flags.length > 0);
    const r = stubRevise(m, dbl, ["Resize the reward"], "economics");
    assert.equal(r.version, 2);
    assert.equal(r.id, dbl.id);
    assert.equal(r.reward.amount, resolveAnchors(m).sized!.amount);
    const v2 = await revise(ctx(tmpDir("propose-rev2")), m, dbl, ["Resize the reward"], "economics", 1);
    assert.equal(v2.version, 2);
    assert.deepEqual(v2.economics!.flags, []);
  });
});
