// buildMock: deterministic assembly of out/<app>/mock from the model directory and whatever screen
// fragments exist (generated by generate.ts, or improved by the QA loop). No LLM here: everything
// interactive comes from window.MODEL (data.js) and the fixed runtime, so a rebuild is always safe.
//
//   index.html     device frame + one <template data-screen="sNN"> per screen
//   data.js        window.MODEL: the subset of the product model the runtime needs
//   design.css     design system (generated; stub from tokens when absent)
//   frame.css, runtime.js, rewarded.js    fixed runtime (copied from src/mock/runtime)
//   screens/sNN.html   the HTML fragment of each render:"html" screen (source of truth for QA)
//   assets/        asset crops, fonts, and screenshots of image screens
//   proposals/Pn.js    window.__PATCHES["Pn"] = { proposal, html } (loaded with ?proposal=Pn)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { Proposal, ProductModel, Screen } from "../core/schema.ts";
import { ensureDir, escapeHtml, writeText } from "../core/io.ts";
import { accentOf, fontFaces, onColor, stubDesignCss } from "./designCss.ts";
import { contextGroups, counterBindings, deviceDp, edgeDeltas, initialCounters, isConsume, startScreen } from "./roles.ts";
import { sanitizeFragment } from "./sanitize.ts";
import { imageScreenHtml, specRender } from "./specRender.ts";

export const RUNTIME_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "runtime");
const RUNTIME_FILES = ["runtime.js", "rewarded.js", "frame.css"];

export interface ProposalHtml { id: string; html: string }
/** A proposal alone (defaults are rendered for its new screens/elements) or with generated fragments. */
export type ProposalInput = Proposal | { proposal: Proposal; html?: ProposalHtml[] };
export interface BuildOptions {
  proposals?: ProposalInput[];
  /** Where screen fragments are read from (default: <outDir>/screens). */
  fragmentsDir?: string;
}

export const fragmentFile = (outDir: string, screenId: string) => path.join(outDir, "screens", `${screenId}.html`);

/** The fragment for an HTML screen: the file on disk, else the spec renderer (written back so QA finds it). */
export function readFragment(m: ProductModel, s: Screen, outDir: string, fragmentsDir = path.join(outDir, "screens")): string {
  const f = path.join(fragmentsDir, `${s.id}.html`);
  if (fs.existsSync(f)) return fs.readFileSync(f, "utf8");
  const html = specRender(s, m);
  writeText(fragmentFile(outDir, s.id), html);
  return html;
}

function copyIfExists(from: string, to: string): boolean {
  if (!fs.existsSync(from)) return false;
  ensureDir(path.dirname(to));
  fs.copyFileSync(from, to);
  return true;
}

/** window.MODEL: only what the runtime needs (no evidence, no economics). */
export function mockData(m: ProductModel) {
  const dev = deviceDp(m);
  const ctx = contextGroups(m);
  const avatar = m.design.assets.find(a => a.kind === "avatar") ?? m.design.assets.find(a => a.kind === "logo");
  const accent = accentOf(m);
  return {
    app: { id: m.app.id, name: m.app.name },
    device: { w: dev.w, h: dev.h, density: dev.density, statusDp: dev.statusDp, navDp: dev.navDp },
    start: startScreen(m),
    accent, onAccent: onColor(accent),
    avatar: avatar ? avatar.file : null,
    screens: m.screens.map(s => ({ id: s.id, name: s.name, kind: s.kind, render: s.render, parent: s.parent, inScope: s.inScope })),
    edges: m.edges.map(e => ({
      id: e.id, from: e.from, to: e.to, el: e.el, transition: e.transition, seen: e.seen, limitHit: !!e.limitHit, consume: isConsume(e),
      deltas: edgeDeltas(e),
      appeared: e.effects.flatMap(f => (f.kind === "appeared" ? [f.text] : [])),
      context: e.context.selected,
    })),
    bindings: m.screens.flatMap(s => counterBindings(s, m).map(b => ({ screen: s.id, el: b.el, resource: b.resource }))),
    counters: initialCounters(m),
    contextGroups: ctx.groups,
    initialSelected: ctx.initial,
    transcripts: m.transcripts,
    walls: m.economy.walls.map(w => ({ id: w.id, edge: w.edge, resource: w.resource, shows: w.shows })),
    externals: m.externals.map(x => ({ id: x.id, kind: x.kind, texts: x.texts.slice(0, 6) })),
  };
}
export type MockData = ReturnType<typeof mockData>;

const STATUS_ICONS = `<svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true"><path fill="currentColor" d="M12 18.5 3 9.5a12.7 12.7 0 0 1 18 0z"/></svg>`
  + `<svg viewBox="0 0 24 24" width="14" height="14" aria-hidden="true"><path fill="currentColor" d="M3 20h3v-4H3zm5 0h3v-8H8zm5 0h3V8h-3zm5 0h3V4h-3z"/></svg>`
  + `<svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true"><path fill="currentColor" d="M16 6H4a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2zm4 3h1a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-1z"/></svg>`;

function proposalScript(input: ProposalInput): { pid: string; js: string } {
  const p = "proposal" in input ? input.proposal : input;
  const frags = "proposal" in input ? input.html ?? [] : [];
  const html: Record<string, string> = {};
  for (const f of frags) {
    // Fragments are model output too: same sanitizing as screens (new screens keep a root, elements don't need one).
    html[f.id] = sanitizeFragment(f.html, f.id, { wrap: p.patch.newScreens.some(s => s.id === f.id) }).html;
  }
  const data = JSON.stringify({ proposal: p, html }).replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
  return { pid: p.id, js: `window.__PATCHES = window.__PATCHES || {};\nwindow.__PATCHES[${JSON.stringify(p.id)}] = ${data};\n` };
}

export function buildMock(m: ProductModel, modelDir: string, outDir: string, o: BuildOptions = {}): string {
  ensureDir(outDir);
  const dev = deviceDp(m);
  for (const f of RUNTIME_FILES) fs.copyFileSync(path.join(RUNTIME_DIR, f), path.join(outDir, f));
  if (!fs.existsSync(path.join(outDir, "design.css"))) writeText(path.join(outDir, "design.css"), stubDesignCss(m));

  // Assets keep their model-relative path ("assets/a001.png"), so fragments can reference them as-is.
  for (const a of m.design.assets) copyIfExists(path.join(modelDir, a.file), path.join(outDir, a.file));
  const fonts = fontFaces(m);
  for (const f of fonts.files) copyIfExists(path.join(modelDir, f.from), path.join(outDir, f.to));

  const templates: string[] = [];
  for (const s of m.screens) {
    let body: string;
    if (s.render === "html") body = readFragment(m, s, outDir, o.fragmentsDir);
    else {
      const rel = `assets/screens/${s.id}${path.extname(s.screenshot) || ".png"}`;
      body = imageScreenHtml(s, m, copyIfExists(path.join(modelDir, s.screenshot), path.join(outDir, rel)) ? rel : null);
    }
    const attrs = [`data-screen="${escapeHtml(s.id)}"`, `data-kind="${s.kind}"`, `data-render="${s.render}"`, `data-name="${escapeHtml(s.name)}"`];
    if (s.parent) attrs.push(`data-parent="${escapeHtml(s.parent)}"`);
    templates.push(`<template ${attrs.join(" ")}>\n${body}\n</template>`);
  }

  writeText(path.join(outDir, "data.js"), `// Generated by src/mock/build.ts from the product model. Read by runtime.js.\nwindow.MODEL = ${JSON.stringify(mockData(m), null, 1)};\n`);

  for (const p of o.proposals ?? []) {
    const { pid, js } = proposalScript(p);
    writeText(path.join(outDir, "proposals", `${pid}.js`), js);
  }

  const htmlCount = m.screens.filter(s => s.render === "html").length;
  const index = `<!doctype html>
<html lang="en" style="--dev-w:${dev.w}px;--dev-h:${dev.h}px;--sb-h:${Math.max(dev.statusDp, 24)}px">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="generator" content="simula mock build (deterministic)">
<title>${escapeHtml(m.app.name)} · interactive mock</title>
<link rel="stylesheet" href="frame.css">
<link rel="stylesheet" href="design.css">
${fonts.css ? `<style id="mock-fonts">\n${fonts.css}\n</style>` : ""}
</head>
<body>
<!-- ${m.screens.length} screens (${htmlCount} HTML, ${m.screens.length - htmlCount} image), ${m.edges.length} edges. Params: ?screen=sNN ?proposal=Pn ?debug=1 ?slide=1 ?frame=0 -->
<div class="mock-stage">
  <div class="mock-device" id="mock-device">
    <div class="mock-screen" id="mock-screen">
      <div class="mock-layers" id="mock-layers"></div>
      <div class="mock-statusbar" aria-hidden="true"><span>09:41</span><span class="mock-sb-icons">${STATUS_ICONS}</span></div>
    </div>
  </div>
</div>
<div id="mock-templates" hidden>
${templates.join("\n")}
</div>
<script src="data.js"></script>
<script src="runtime.js"></script>
<script src="rewarded.js"></script>
</body>
</html>
`;
  const indexFile = path.join(outDir, "index.html");
  writeText(indexFile, index);
  return indexFile;
}
