// out/README.md: the results gallery for readers on GitHub, who can't open out/index.html without
// cloning. GitHub renders this file when you browse into out/, so it shows each app's headline
// numbers, the shipped flow slides, the QA side-by-sides (the real app vs. the mock) and links to
// every Markdown artifact. Relative paths only; nothing here is fetched.
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import type { ProductModel } from "../core/schema.ts";
import type { QaDigest } from "./data.ts";
import { one } from "./numbers.ts";

export interface GalleryRow {
  id: string;
  name: string;
  profile: string;
  state: string;
  why: string;
  model: ProductModel | null;
  qa: QaDigest | null;
  verdicts: { SHIP: number; REVISE: number; REJECT: number } | null;
  ships: { id: string; title: string }[];
  stubs: string[];
  notes: string[];
}

const MAX_FLOWS = 4;
const MAX_QA = 6;

export function galleryMd(all: GalleryRow[], root: string): string {
  // Links to git-ignored outputs (a locally regenerated demo) would be dead on GitHub: leave them out.
  const rows = all.filter(r => !gitIgnored(path.join(root, r.id)));
  const L: string[] = [
    "# Results",
    "",
    "One section per app, all produced by the same pipeline with no per-app code. This page is generated by `npm run report` (the full interactive report is `out/index.html`; clone the repo and open it, since the mock and the QA report are HTML).",
    "",
    "| App | State | Explored | Regime | Verdicts | QA fidelity · flows |",
    "|---|---|---|---|---|---|",
  ];
  for (const r of rows) {
    const c = r.model?.coverage;
    L.push(`| [${r.name}](#${anchor(r.name)}) | ${r.state}${r.stubs.length ? ` (stub: ${r.stubs.join(", ")})` : ""} | ${c ? `${c.states} screens · ${c.edges} transitions` : "–"} | ${r.model?.regime ?? "–"} | ${r.verdicts ? `${r.verdicts.SHIP} SHIP · ${r.verdicts.REVISE} REVISE · ${r.verdicts.REJECT} REJECT` : "–"} | ${r.qa ? `${r.qa.compositeMean?.toFixed(2) ?? "–"} · ${r.qa.flowPassed}/${r.qa.flowTotal}` : "–"} |`);
  }

  for (const r of rows) {
    const dir = path.join(root, r.id);
    const has = (...xs: string[]) => fs.existsSync(path.join(dir, ...xs));
    const rel = (...xs: string[]) => [r.id, ...xs].join("/");
    L.push("", `## ${r.name}`, "");
    if (!r.model) {
      L.push(`**${r.state}.** ${r.why || "No outputs yet."}`);
      for (const n of r.notes) L.push(`- ${one(n)}`);
      continue;
    }
    L.push(`${one(r.model.brief.oneLiner)} Regime: **${r.model.regime}**. Profile: ${r.profile || "–"}.`, "");
    const links = [
      ["Numbers", "NUMBERS.md"], ["Product model digest", "model/digest.md"], ["Candidates", "proposals/candidates.md"],
      ["Judgments (every score, with evidence)", "proposals/judgments.md"], ["Judge self-check", "proposals/judge-eval.md"],
      ["Trajectory", "trajectory.md"], ["Slides (PDF)", "slides/deck.pdf"],
    ].filter(([, f]) => has(...f.split("/")));
    if (links.length) L.push(links.map(([label, f]) => `[${label}](${rel(...f.split("/"))})`).join(" · "), "");

    const pngDir = path.join(dir, "slides", "png");
    const pngs = fs.existsSync(pngDir) ? fs.readdirSync(pngDir).filter(f => f.endsWith(".png")).sort() : [];
    const flows = pngs.filter(f => /flow-P\d+\.png$/.test(f));
    const gifs = fs.existsSync(path.join(dir, "slides")) ? fs.readdirSync(path.join(dir, "slides")).filter(f => /^flow-P\d+\.gif$/.test(f)) : [];
    for (const g of gifs) {
      const pid = /flow-(P\d+)\.gif$/.exec(g)![1];
      const title = one(r.ships.find(s => s.id === pid)?.title ?? pid);
      L.push(`### ${pid} in motion`, "", `<img src="${rel("slides", g)}" width="300" alt="${pid}: ${title.replace(/"/g, "&quot;")}, played in the generated mock">`, "",
        `_The lead flow played in the generated mock: today → what changed → the offer → the game → the reward confirmed in-app._`, "");
    }
    if (flows.length) {
      L.push("### Shipped flows", "");
      for (const f of flows.slice(0, MAX_FLOWS)) {
        const pid = /flow-(P\d+)\.png$/.exec(f)![1];
        const title = one(r.ships.find(s => s.id === pid)?.title ?? pid);
        L.push(`**${pid}: ${title}**`, "", `![${pid}: ${title}](${rel("slides", "png", f)})`, "");
      }
      if (flows.length > MAX_FLOWS) L.push(`…and ${flows.length - MAX_FLOWS} more in [the deck](${rel("slides", "deck.pdf")}).`, "");
    }
    const lead = pngs.find(f => /recommendation\.png$/.test(f));
    if (lead) L.push("<details><summary>Recommendation slide</summary>", "", `![Recommendation](${rel("slides", "png", lead)})`, "", "</details>", "");

    if (r.qa?.screens.length) {
      const shots = r.qa.screens.filter(s => has("qa", s.id, "original.png") && has("qa", s.id, "best.png")).slice(0, MAX_QA);
      if (shots.length) {
        L.push("### Mock fidelity (real app vs. generated mock)", "", "| Screen | Real app | Mock | Score |", "|---|---|---|---|");
        for (const s of shots) {
          L.push(`| ${one(s.name).replace(/\|/g, "\\|")} | <img src="${rel("qa", s.id, "original.png")}" width="180"> | <img src="${rel("qa", s.id, "best.png")}" width="180"> | ${s.composite?.toFixed(2) ?? "–"} (${s.render}) |`);
        }
        L.push("", `Composite = 0.35·layout IoU + 0.25·SSIM + 0.20·text + 0.20·color. Flow QA: ${r.qa.flowPassed}/${r.qa.flowTotal} navigation edges replay correctly.`);
      }
    }
    if (r.notes.length) L.push("", "**Human notes:**", "", ...r.notes.map(n => `- ${one(n)}`));
  }
  return L.join("\n") + "\n";
}

function gitIgnored(dir: string): boolean {
  try {
    return spawnSync("git", ["check-ignore", "-q", dir], { cwd: path.dirname(dir), stdio: "ignore" }).status === 0;
  } catch {
    return false;
  }
}

function anchor(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9 -]/g, "").trim().replace(/ /g, "-");
}
