// out/<app>/NUMBERS.md: the numbers card. Every figure a reviewer or a recording needs for one app
// (coverage, the measured caps, the exchange rate, verdicts with a rejected example, the judge's
// self-check, QA fidelity, model calls), read from the artifacts and never typed by hand. Written by
// the report stage next to the app's outputs, so it is always in step with the last run.
import { exchangeRateLine } from "../model/economics.ts";
import type { Candidates, Judgments, ProductModel } from "../core/schema.ts";
import { fmtTokens, fmtUsd, type CostRollup, type QaDigest, type TraceStats } from "./data.ts";

export interface NumbersInput {
  name: string;
  model: ProductModel | null;
  qa: QaDigest | null;
  cands: Candidates | null;
  judgments: Judgments | null;
  evalMd: string;
  cost: CostRollup;
  trace: TraceStats;
  notes: string[];
  stubs: string[];
}

export function numbersMd(x: NumbersInput): string {
  const L: string[] = [`# ${x.name}: numbers`, "", "_Generated by `npm run report` from this app's artifacts. Re-run it after any stage to refresh._", ""];
  const m = x.model;
  if (x.stubs.length) L.push(`> ⚠ Produced by deterministic stubs, not a model: **${x.stubs.join(", ")}**. Re-run those stages with a key (or after the free quota resets) for model-written output.`, "");

  L.push("## Exploration", "");
  if (m) {
    const c = m.coverage;
    L.push(`- **${c.states} screens, ${c.edges} transitions**, ${c.externals} external surface${c.externals === 1 ? "" : "s"}, in ${c.steps} steps (${c.minutes.toFixed(0)} min). Stopped: ${c.stopReason}.`);
    L.push(`- Human interventions: ${Math.max(c.humanInterventions, x.trace.human)}.`);
    if (c.notExplored.length) L.push(`- Deliberately not explored: ${c.notExplored.length} (${[...new Set(c.notExplored.map(n => n.why))].slice(0, 3).join("; ")}).`);
  } else L.push("- No product model yet.");

  if (m) {
    const e = m.economy;
    L.push("", "## Economy", "", `- Regime: **${m.regime}**.`);
    L.push(`- ${e.resources.length} resources · ${e.sinks.length} sinks · ${e.sources.length} sources · ${e.offers.length} offers · ${e.walls.length} walls · ${e.ads.length} ad placements.`);
    for (const r of e.resources) {
      const src = e.sources.find(s => s.resource === r.id && s.amount != null);
      const sink = e.sinks.find(k => k.resource === r.id);
      const cap = src?.amount != null ? `free allowance ${src.amount}${src.cadence !== "unknown" ? ` (${src.cadence})` : ""}` : r.observedValues.length ? `seen at ${r.observedValues.slice(0, 4).join(", ")}` : "no amount seen";
      L.push(`- **${r.name}** (${r.kind}): ${cap}${sink ? `; "${sink.action}" costs ${sink.amount} ${r.unit ?? ""}`.trimEnd() : ""}.`);
    }
    for (const u of e.derived?.unitsPerView ?? []) {
      const line = exchangeRateLine(m, u.resource);
      if (line) L.push(`- Exchange rate: **${line}**.`);
    }
    const screenName = (id: string) => m.screens.find(s => s.id === id)?.name ?? id;
    for (const w of e.walls.slice(0, 4)) L.push(`- Wall: blocks "${w.blockedIntent}", shows ${/^s\d+$|^N\d+$/.test(w.shows) ? screenName(w.shows) : `"${w.shows}"`}.`);
    for (const o of e.offers.slice(0, 4)) L.push(`- Offer: ${o.label} (${o.priceText}).`);
  }

  L.push("", "## Proposals and verdicts", "");
  if (x.judgments) {
    const final = latestFinal(x.judgments);
    const n = (v: string) => final.filter(f => f.verdict === v).length;
    L.push(`- **${n("SHIP")} SHIP / ${n("REVISE")} REVISE / ${n("REJECT")} REJECT** from ${final.length} proposals (${x.judgments.rounds.length} judge rounds, at most ${x.judgments.thresholds.maxRounds} blind revisions each).`);
    if (x.cands) L.push(`- Obvious baseline ideas written first, to beat: ${x.cands.baseline.length}. Ideas considered: ${x.cands.ideas.length}; proposals written: ${x.cands.proposals.length}.`);
    for (const f of final) {
      const p = x.cands?.proposals.find(q => q.id === f.proposalId);
      L.push(`- ${f.proposalId} **${f.verdict}**${f.weighted != null ? ` (${f.weighted.toFixed(2)})` : ""}: ${p?.title ?? f.summary}${p ? ` [${p.case}]` : ""}.`);
    }
    const notShipped = final.filter(f => f.verdict !== "SHIP");
    if (notShipped.length) {
      L.push("", "**Why the others did not ship** (last round per proposal):", "");
      for (const f of notShipped) {
        const r = [...x.judgments.rounds].reverse().find(q => q.proposalId === f.proposalId);
        const failed = r?.gates.filter(g => !g.pass).map(g => g.gate) ?? [];
        const why = [r?.topConcern, ...(r?.reasons.slice(0, 2) ?? [])].filter(Boolean).join(" · ");
        L.push(`- ${f.proposalId} (${f.verdict}): ${why || f.summary}${failed.length ? ` Failed gates: ${failed.join(", ")}.` : ""}`);
      }
    }
  } else L.push("- Not judged yet.");

  L.push("", "## Judge self-check", "");
  const neg = /Negatives caught[^*]*\*\*(\d+) \/ (\d+)\*\*([^\n]*)/.exec(x.evalMd);
  const pos = /Positives that SHIP: \*\*(\d+) \/ (\d+)\*\*/.exec(x.evalMd);
  if (neg || pos) {
    if (neg) L.push(`- Caught **${neg[1]} of ${neg[2]}** single-fault broken proposals${neg[3].replace(/\.$/, "")}.`);
    if (pos) L.push(`- Shipped **${pos[1]} of ${pos[2]}** known-good proposals.`);
  } else L.push("- Not run for this app (`npm run eval:judge`).");

  L.push("", "## Mock and QA", "");
  if (x.qa) {
    L.push(`- Mean fidelity (composite 0–1): **${x.qa.compositeMean != null ? x.qa.compositeMean.toFixed(2) : "–"}** over ${x.qa.screens.length} screens; ${x.qa.htmlShare != null ? `${Math.round(x.qa.htmlShare * 100)}%` : "–"} rebuilt as HTML.`);
    L.push(`- Flow QA: **${x.qa.flowPassed} / ${x.qa.flowTotal}** navigation edges replay correctly in the mock.`);
    const best = [...x.qa.screens].filter(s => s.composite != null).sort((a, b) => b.composite! - a.composite!);
    if (best.length) L.push(`- Best: ${best[0].name} (${best[0].composite!.toFixed(2)}). Weakest: ${best[best.length - 1].name} (${best[best.length - 1].composite!.toFixed(2)}).`);
    for (const f of x.qa.failures.slice(0, 3)) L.push(`- Flow miss: ${f.edge}: ${f.reason}`);
  } else L.push("- QA not run yet.");

  L.push("", "## Cost", "");
  const c = x.cost;
  L.push(`- **${fmtUsd(c.usd)}**, ${c.live} live model call${c.live === 1 ? "" : "s"} (+${c.cached} served from cache), ${fmtTokens(c.tokensIn)} tokens in, ${fmtTokens(c.tokensOut + c.thoughts)} out${c.providers.includes("gemini") ? " (free Gemini tier)" : ""}.`);
  if (c.models.length) L.push(`- Models that answered: ${c.models.join(", ")}.`);
  for (const s of c.byStage) L.push(`- ${s.stage}: ${s.live} live, ${s.cached} cached.`);
  L.push(`- Trace: ${x.trace.decisions} decisions, ${x.trace.failures} failures, ${x.trace.recoveries} recoveries.`);

  if (x.notes.length) L.push("", "## Human notes", "", ...x.notes.map(n => `- ${n}`));
  return L.join("\n") + "\n";
}

function latestFinal(j: Judgments) {
  const by = new Map<string, Judgments["final"][number]>();
  for (const f of j.final) by.set(f.proposalId, f);
  return [...by.values()];
}
