// candidates.md: what the proposer produced, readable by a product person. The first table has an
// EMPTY label column so a human can label the proposals blind, before the judge runs.
import type { Candidates, ProductModel, Proposal } from "../core/schema.ts";
import { exchangeRateLine } from "../model/economics.ts";

const cell = (s: string | number | undefined | null) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");

export function screenName(m: ProductModel, id: string): string {
  const s = m.screens.find(x => x.id === id);
  return s ? `${s.name} (${id})` : id;
}

export function rewardLine(p: Proposal): string {
  return [p.reward.what, p.reward.duration && !p.reward.what.includes(p.reward.duration) ? `for ${p.reward.duration}` : ""].filter(Boolean).join(" ");
}

export function economicsLines(p: Proposal, m: ProductModel): string[] {
  const e = p.economics;
  if (!e) return ["- Economics: not computed."];
  const rate = p.reward.resource ? exchangeRateLine(m, p.reward.resource) : null;
  const usd = (n: number | null) => (n == null ? "n/a" : `$${n.toFixed(4)}`);
  return [
    rate ? `- Exchange rate: ${rate}.` : "- Exchange rate: n/a (the reward is not a priced resource).",
    `- One completed US view earns ${usd(e.viewValueUsd[0])}–${usd(e.viewValueUsd[1])}; the reward is worth ${usd(e.rewardValueUsdAtList)} at list (${e.rewardToViewRatio ?? "n/a"}x a view); max per day ${usd(e.maxDailyEarnUsdAtList)} vs cheapest pack ${e.cheapestPaidUnitUsd != null ? `$${e.cheapestPaidUnitUsd}` : "n/a"}.`,
    `- Cost to serve per view: ${usd(e.cogsPerViewUsd)} (${p.assumptions.cogs} x ${p.assumptions.cogsUnitsPerView}).`,
    `- ${e.scenario.label} Impressions/DAU ${e.scenario.impressionsPerDau}, ARPDAU $${e.scenario.arpdauUsd}.`,
    e.flags.length ? `- **Flags:** ${e.flags.join(" ")}` : "- Flags: none.",
  ];
}

export function proposalMd(p: Proposal, m: ProductModel): string {
  const L: string[] = [];
  L.push(`### ${p.id} v${p.version}: ${p.title}`, "", `> ${p.oneLiner}`, "");
  L.push(`- **Case:** ${p.case} · **Archetype:** ${p.archetype} · **Beyond baseline:** ${p.beyondBaseline ? "yes" : "no"}`);
  L.push(`- **Anchor:** moments ${p.anchor.moments.join(", ") || "none"}; economy ${p.anchor.economy.join(", ") || "none"}`);
  if (p.anchor.newMechanic) {
    const n = p.anchor.newMechanic;
    L.push(`- **New mechanic:** ${n.name}: ${n.description} Why: ${n.whyNeeded}${n.removesFreeValue ? " **Removes free value (high risk).**" : ""}`);
  }
  L.push(`- **Surface:** ${screenName(m, p.surface)} · **Trigger:** ${p.trigger}`);
  L.push(`- **Eligibility:** ${p.eligibility}`);
  L.push(`- **Offer:** "${p.offer.title}" / "${p.offer.body}" / [${p.offer.cta}] [${p.offer.decline || "(no decline)"}]`);
  L.push(`- **Simula:** ${p.simula.unit}, entry ${p.simula.entry}${p.simula.gamePartner ? `, Game Partner: ${p.simula.gamePartner}` : ""}, min play ${p.simula.minPlaySec} s, grant on ${p.reward.grantOn}`);
  L.push(`- **Reward:** ${rewardLine(p)} · **Caps:** ${p.caps.perDay}/day, cooldown ${p.caps.cooldownMin} min`);
  L.push(`- **Cannibalization guard:** ${p.cannibalizationGuard}`);
  L.push(...economicsLines(p, m));
  L.push(`- **KPIs:** ${p.kpis.primary}. Guardrails: ${p.kpis.guardrails.join("; ")}. Holdout: ${p.kpis.holdout}`);
  L.push(`- **Precedents:** ${p.precedents.join(", ")} · **Risks:** ${p.risks.join(" ")}`);
  if (p.evidence.length) L.push(`- **Evidence:** ${p.evidence.map(e => `${e.obs}${e.el ? `/${e.el}` : ""}${e.quote ? ` "${e.quote}"` : ""}${e.verified ? " ✓" : " (unverified)"}`).join("; ")}`);
  const pt = p.patch;
  L.push("", "**Patch**", "");
  for (const s of pt.newScreens) L.push(`- new ${s.kind} \`${s.id}\`${s.basedOn ? ` based on ${screenName(m, s.basedOn)}` : ""}: ${s.change}`);
  for (const e of pt.newElements) L.push(`- new element \`${e.id}\` in ${screenName(m, e.in)} ${e.place} ${e.near ?? "(no anchor)"}: ${e.change}`);
  for (const e of pt.newEdges) L.push(`- edge ${e.from}/${e.el} → ${e.to}${e.effects.length ? ` (${e.effects.map(f => `${f.resource} ${f.delta > 0 ? "+" : ""}${f.delta}`).join(", ")} on REWARD_VERIFIED)` : ""}${e.guard ? ` when ${e.guard.resource} < ${e.guard.lt}` : ""}`);
  L.push("", "**Storyboard**", "", "| # | phase | screen | overlay | counters | callouts | caption |", "|---|---|---|---|---|---|---|");
  p.storyboard.forEach((b, i) => L.push(`| ${i + 1} | ${b.phase} | ${cell(screenName(m, b.screen))} | ${b.overlay} | ${cell(b.counters.map(x => `${x.resource}=${x.value}`).join(", "))} | ${cell(b.callouts.map(x => `${x.node}: ${x.text}`).join("; "))} | ${cell(b.caption)} |`));
  return L.join("\n");
}

export function candidatesMd(c: Candidates, m: ProductModel, violations: string[] = []): string {
  const L: string[] = [];
  L.push(`# Rewarded-ad candidates: ${m.app.name}`, "");
  if (c.generatedBy === "stub") L.push("> **Generated by the deterministic stub (no LLM).** Templates over the model's moments and economy; see src/propose/stub.ts.", "");
  L.push(`Regime (computed): **${m.regime}**. ${c.ideas.length} ideas, ${c.proposals.length} written up.`, "");

  L.push("## Blind labels (fill in before reading the judgments)", "");
  L.push("Label each proposal SHIP, REVISE or REJECT from the write-ups below, before running `judge`. Copy the labels to `proposals/labels.json` as `[{\"id\":\"P1\",\"label\":\"SHIP\"}]`.", "");
  L.push("| id | title | case | archetype | surface | reward | your label (SHIP/REVISE/REJECT) |", "|---|---|---|---|---|---|---|");
  for (const p of c.proposals) L.push(`| ${p.id} | ${cell(p.title)} | ${p.case} | ${p.archetype} | ${cell(screenName(m, p.surface))} | ${cell(rewardLine(p))} |  |`);

  L.push("", "## The obvious baseline (the bar to beat)", "");
  for (const b of c.baseline) L.push(`- ${b}`);

  L.push("", "## Moment sweep", "", "| moment | type | screen | value exchange | viable |", "|---|---|---|---|---|");
  for (const s of c.momentSweep) {
    const mo = m.moments.find(x => x.id === s.moment);
    L.push(`| ${s.moment} | ${mo?.type ?? "?"} | ${cell(mo ? screenName(m, mo.screen) : "")} | ${cell(s.exchange)} | ${s.viable ? "yes" : "no"} |`);
  }

  L.push("", "## All ideas", "", "| # | title | case | archetype | moment | reward | beyond baseline | selected because |", "|---|---|---|---|---|---|---|---|");
  c.ideas.forEach((i, k) => {
    const sel = c.selected.find(s => s.index === k);
    L.push(`| ${k} | ${cell(i.title)} | ${i.case} | ${i.archetype} | ${i.moment} | ${cell(i.reward)} | ${i.beyondBaseline ? "yes" : "no"} | ${cell(sel?.why ?? "")} |`);
  });
  L.push("", "## Set checks (validateSet)", "", violations.length ? violations.map(v => `- ${v}`).join("\n") : "All checks pass.");

  L.push("", "## Proposals", "");
  for (const p of c.proposals) L.push(proposalMd(p, m), "");
  return L.join("\n") + "\n";
}
