// scratch: compiled model -> mock -> qa (stub)
import fs from "node:fs";
import path from "node:path";
import { setLlmContext } from "../../src/core/llm.ts";
import { loadProfile, paths } from "../../src/core/config.ts";
import type { StageCtx } from "../../src/core/run.ts";
import { understand } from "../../src/model/understand.ts";
import { generateMock } from "../../src/mock/generate.ts";
import { runQa } from "../../src/qa/loop.ts";
import { writeSampleGraph } from "./model-sample-graph.ts";
setLlmContext({ mode: "stub" });
const tmp = "/tmp/claude-0/-home-user-simula/25c848c5-fa91-54b9-9b9c-b7d1ed4ee763/scratchpad/mockqa/compiled";
fs.rmSync(tmp, { recursive: true, force: true });
const { graphFile } = await writeSampleGraph(path.join(tmp, "run"), { adCard: true });
const c: StageCtx = { app: { id: "sample", package: "web.sample", name: "SampleChat", profile: "fixture", login: "none" }, profile: loadProfile("fixture"), paths: paths("sample", { outRoot: path.join(tmp, "out") }), runId: "t", llm: "stub", opts: {} };
const { model } = await understand(c, graphFile);
console.log(model.screens.map(s => `${s.id} ${s.name} ${s.kind} ${s.render} els=${s.elements.length} bind=${JSON.stringify(s.bindings)}`).join("\n"));
console.log(model.edges.map(e => `${e.id} ${e.from}->${e.to} el=${e.el} ${e.transition} ${JSON.stringify(e.effects.filter(f=>f.kind==="counter").map((f:any)=>f.delta))} ctx=${e.context.selected} lim=${e.limitHit??""}`).join("\n"));
const t0 = Date.now();
await generateMock(c, model, c.paths.model);
console.log("mock", Date.now() - t0);
const sum = await runQa(c, model, c.paths.model, {});
console.log(JSON.stringify(sum, null, 1));
console.log("qa", Date.now() - t0);
